version: "3.8"

services:
  db:
    image: postgres:13
    volumes:
      - ./export:/export
      - postgres_data:/data/db
    environment:
      - POSTGRES_USER=justas
      - POSTGRES_PASSWORD=bac
      - POSTGRES_DB=finance_app_data
    ports:
      - 5432:5432
  adminerUi:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  postgres_data:
