version: "3.8"

services:
  web:
    build: .
    command: flask run --host 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=justasb
      - POSTGRES_PASSWORD=bace
      - POSTGRES_DB=finance_app_data
    ports:
      - 5432:5432
  adminerUi:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  postgres_data:
    name: finance_app
