"""empty message

Revision ID: 15af01c0265a
Revises: 95af5118acf3
Create Date: 2023-08-11 10:46:53.424189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15af01c0265a'
down_revision = '95af5118acf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_savings', schema=None) as batch_op:
        batch_op.drop_constraint('monthly_savings_month_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_savings', schema=None) as batch_op:
        batch_op.create_unique_constraint('monthly_savings_month_key', ['month'])

    # ### end Alembic commands ###
