"""empty message

Revision ID: 164746710e1c
Revises: eb7dbc376bd2
Create Date: 2023-08-12 10:06:51.197619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164746710e1c'
down_revision = 'eb7dbc376bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saving_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saving_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by_id')

    # ### end Alembic commands ###
