"""empty message

Revision ID: 1e9bed564876
Revises: 1fb54cda8de1
Create Date: 2023-08-13 11:56:50.281053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e9bed564876'
down_revision = '1fb54cda8de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saving_plans', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_total_balance', sa.Float(), nullable=True))
        batch_op.drop_column('total_balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('initial_total_balance')

    with op.batch_alter_table('saving_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.VARCHAR(length=40), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
