"""empty message

Revision ID: ab58a82ece80
Revises: 574eb595332a
Create Date: 2023-08-10 16:58:00.545092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab58a82ece80'
down_revision = '574eb595332a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incomes')
    op.drop_table('spendings')
    op.drop_table('total_balances')
    with op.batch_alter_table('finance_data', schema=None) as batch_op:
        batch_op.drop_constraint('finance_data_month_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_data', schema=None) as batch_op:
        batch_op.create_unique_constraint('finance_data_month_key', ['month'])

    op.create_table('total_balances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('currency_code', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='total_balances_created_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='total_balances_pkey'),
    sa.UniqueConstraint('month', name='total_balances_month_key')
    )
    op.create_table('spendings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('currency_code', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='spendings_created_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='spendings_pkey'),
    sa.UniqueConstraint('month', name='spendings_month_key')
    )
    op.create_table('incomes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('currency_code', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='incomes_created_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='incomes_pkey'),
    sa.UniqueConstraint('month', name='incomes_month_key')
    )
    # ### end Alembic commands ###
