"""empty message

Revision ID: eb6ebbd0adee
Revises: 131c81dc9937
Create Date: 2023-08-12 12:38:12.943950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb6ebbd0adee'
down_revision = '131c81dc9937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_total_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('updated_total_balance', sa.Float(), nullable=True))
        batch_op.drop_column('total_balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('updated_total_balance')
        batch_op.drop_column('initial_total_balance')

    # ### end Alembic commands ###
