"""empty message

Revision ID: eb7dbc376bd2
Revises: 15af01c0265a
Create Date: 2023-08-12 10:02:32.816437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb7dbc376bd2'
down_revision = '15af01c0265a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saving_plans', schema=None) as batch_op:
        batch_op.drop_constraint('saving_plans_created_by_id_fkey', type_='foreignkey')
        batch_op.drop_column('created_by_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saving_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('saving_plans_created_by_id_fkey', 'users', ['created_by_id'], ['id'])

    # ### end Alembic commands ###
